kriszyp/msgpackr

- pack.js
When running in environments like the `jsdom` environment provided by default with Jest, there is no `TextEncoder` global, so the `encoder` object is not defined and `encoder.encodeInto` triggers a `TypeError: Cannot read property 'encodeInto' of undefined`.
> check that encoder is defined before checking for encodeInto property

- index.d.ts
- pack.d.ts
- unpack.d.ts
Using an enum is a little easier for this numeric option:
```typescript
import {Packr, FLOAT32_OPTIONS} from "msgpackr";
const p = new Packr({
useFloat32: FLOAT32_OPTIONS.ALWAYS
});
```
> Use enum for FLOAT32 options

- pack.js
Allows build tools (e.g. webpack) to parse this file without a loader
> Replace bigint literals

- browser.mjs
Removes an import that cannot be resolved by e.g. webpack and doesn't seem to be used or have any effect.
> Remove unused

- package.json
this package is pointing to the index.js that is on the root level, we should only expose the dist files, this pr tries to fix this. Also you can run npm run dry-run to see which files are going to be exposed in npm
> fix(dist): only expose dist files

- pack.js
- tests/test.js
- unpack.d.ts
Using a custom onInvalidDate previously caused an error because the codepath never called `allocateForWrite`, resulting in `target` staying `null`. I'm not sure if `allocateForWrite(0)` is a _good_ solution for this since I'm not very familiar with the codebase – it might be better to wrap the `pack` passed to extensions such that it checks if `allocateForWrite` hasn't been called and restores `target` if so.
> Fix issues with onInvalidDate

- README.md
[Rendered](https://github.com/kriszyp/msgpackr/blob/638818e3f87f2a1be777ab6a88cc4bcc140c8a92/README.md)
vs
If you want it below the "Basic Usage" header, place the HTML immediately after the `# Basic Usage` line.
> fix image float in README.md

- struct.js
- unpack.js
It's a breaking change for optional chain and it's not support in node v12 & v14. Users are still using lower versions of node. This package does not declare an engines scope in package.json.
Some package like bull support from node v10, I think it keep compatible will be perfect.
> fix: optional chain unsupport under node v16

- pack.js
- struct.js
Node's "vm" module allows the creation of sandboxes that don't share globals with the host. This includes Array, Function, etc. When using msgpackr inside a VM to `pack` messages coming from outside the VM, the constructor won't be "Array" (as defined in the VM).
To properly identify arrays, msgpackr should use Array.isArray. This function should find the same arrays as "instanceof Array", and more. We keep the "instanceof" check just in case this turns out to be wrong.
Creating a test for this is tricky as this requires running msgpackr inside the VM (eg: with bundling).
Repro code:
```
const { pack, unpack } = require('msgpackr');
console.log(unpack(pack(args)));
```
Create the bundle:
`npx esbuild --bundle script.js > bundle.js`
Run bundle.js inside a VM, and pass it a "complex" args …
> Add support for Arrays crossing a VM boundary

- README.md
- index.d.cts
- index.d.ts
- tests/test.js
- unpack.js
I need int64s/uint64s as strings instead of bigints for compatibility with other libraries, which isn't something any other messagepack library can do.
> Add int64AsType option

- unpack.js
We went down a rabbit hole in our project as the JSON.stringify error for a BigInt hid the true error.
> Safely stringify bigints for error messages

- README.md
- tests/test.js
- unpack.js
This PR adds `numberOrBigInt` value to `int64AsType` option which dynamically decodes (u)int64 based on value magnitude either as number of bigint. Values within safe (u)int range [-2**53...2**53] are returned as number and everything else as bigint,
This PR does not affect the current behaviour and must explicitly enabled to change behaviour.
The current options string `numberOrBigInt` is rather long so if a better keyword is found I would prefer it.
> Additional type for int64AsType option

- README.md
- tests/test.js
- unpack.js
As discussed in #101 I've refactored the option value 'numberOrBigInt' to 'auto' which is more succinct
> Refactor new `int64AsType` option value 'numberOrBigInt' to 'auto'

- package.json
I moved `types` condition to the front. `package.json#exports` are **order-sensitive** - they are always matched from the top to the bottom. When a match is found then it should be used and no further matching should occur. 
Right now, the current setup works in TypeScript but it's considered a bug and it should not be relied upon, see the thread and the comment [here](https://github.com/microsoft/TypeScript/issues/50762#issuecomment-1528318260). For that reason, I would like to fix all popular packages that misconfigured their `exports` this way so the bug can be fixed in TypeScript.
Additionally I added proper `.d.cts` files for `/pack` and `/unpack`, that should also fix "👺 Masquerading as ESM" and "⚠️ ESM (dynamic import only)", see reported errors …
> move `types` condition to the front and add proper `d.cts` files for `/pack` and `/unpack`

- README.md
- index.d.ts
- tests/test.js
- unpack.js
We are switching to msgpackr for packing and unpacking the streams at scrimba.com. We have streams of thousands of individual values. During decoding we need to know the actual offset of each object. Since msgpackr is so optimized (yay!) there's no simple way to retrieve that. Msgpackr reuses local variables to keep track of position.
The most natural interface I could come up with that does not impact performance in any way is to only allow peeking into these internals when you provide a callback to unpackMultiple. This PR includes the offset of each read value as the second argument, and the length (number of bytes of the encoded value) as the third argument. I ended up calling these arguments `start` and `size` in the typings (and readme), but open to changing them to something more …
> Added optional offset and size parameters to unpackMultiple

- pack.js
- tests/test.js
We are using custom extensions to pack domain-specific objects with msgpackr. Some of the items we are trying to pack are instantiated as functions, where we change the prototype of the function to a class. I know this is _not_ a common pattern, and it would probably not make sense for msgpackr to support serializing these types of objects out of the box.
What happens is that even if our objects respond true to things like `myobject instanceof CustomFilter`, and correctly inherits all the characteristics of `CustomFilter.prototype`, the object still looks like a function to msgpackr since `typeof myobject == 'function'`. I saw in the source-code that when msgpackr tries to pack a function it calls `packr.writeFunction` if this exists. But, there is no way to get a reference to the actual …
> Include value as parameter of writeFunction

- index.d.ts
Previous interface was throwing `node_modules/msgpackr/index.d.ts:10:24 - error TS1385: Function type notation must be parenthesized when used in a union type.`
> fix: function declaration in `index.d.ts` file

- pack.js
- tests/test.js
For reasons outside of my control, someone might return `this` when implementing `toJSON` causing the packing logic to go into an infinite loop.
This commit implements a guard against this specific case. The logic will continue through if `value.toJSON() === value`.
> avoid recursion when packing with toJSON

- pack.js
- tests/test.js
- unpack.js
resolves https://github.com/kriszyp/msgpackr/issues/130
> feat: Add support for serializing Error causes

- index.d.ts
- index.js
Hi there,
This PR exposes the following flags:
- `REUSE_BUFFER_MODE`
- `RESET_BUFFER_MODE`
- `RESERVE_START_SPACE`
It also exposes these to TypeScript:
```typescript
export class Packr extends Unpackr {
// ...
offset: number;
useBuffer(buffer: Buffer): void;
clearSharedData(): void;
}
```
Let me know if something's missing so I can improve this PR. 
Thank you for the great work on this lib @kriszyp, cheers! 💙
> Expose Packr flags + TypeScript fixes

- index.d.ts
- pack.js
- package.json
I have a use-case where I pre-fill a `Buffer` with data, and append a msgpack-encoded message to it. As I re-use the same buffer, its "position" tend to grow indefinitely, so I need to restart its internal "position" before calling `.pack()`.
Example:
```typescript
const buffer = Buffer.allocUnsafe(1024);
// initialize (once)
const packr = new Packr();
packr.useBuffer(buffer);
// write and consume these (multiple times)
packr.position = 0; // re-set packr position
buffer[0] = 0; // ... write my own first bytes
const packedData = packr.pack({message: "hello world"}, 2048 + 1); // pack data following bytes on existing buffer
// get subarray of full initial bytes + msgpack encoded
buffer.subarray(0, packedData.byteLength);
```
> allow to get/set 'position' of encoding buffer

- README.md
- pack.js
- tests/test.js
I would like to drop keys with null/undefined values from objects. It would be preferable to not need to strip these values first and simply skip over them when packing. When unpacking into fixed data types, missing keys can be initialised with defaults. I've proposed adding a sparse option in this pr.
> add sparse option to drop null/undefined from objects

- pack.js
Fixes SyntaxError on older devices #141
> Replace BigInt Syntax

- pack.js
If use this library from Clojurescript with target :browser - following error arrives. It somehow connected to Google Closure Compiler. Fix is pretty easy - just change from 'var' to 'let' variable definition, so looks like it connected to variable scope definition. 
```
Failed to convert sources
{:tag :shadow.build.closure/convert-error, :sources [[:shadow.build.npm/resource "node_modules/msgpackr/pack.js"]]}
ExceptionInfo: failed to convert sources
shadow.build.closure/convert-sources-simple*/fn--13161 (closure.clj:2073)
shadow.build.closure/convert-sources-simple* (closure.clj:2060)
shadow.build.closure/convert-sources-simple* (closure.clj:1924)
shadow.build.closure/convert-sources-simple (closure.clj:2234)
shadow.build.closure/convert-sources-simple (closure.clj:2184) …
```
> fix: Google Closure Compiler internal compiler error(used by Clojurescript)

- README.md
- index.d.ts
- pack.js
- tests/test.js
There is already the `largeBigIntToFloat` config option which serializes bigints which exceed 2^64 as floats, but this loses precision.
So this PR adds the `largeBigIntToString` which serializes bigints which exceed 2^64 as strings, resulting in no lose of precision.
Obviously serializing these numeric values as strings is not as compact as it could be, but in many cases that is an ok price to pay and is more than made up for by the simplicity, eg. you can convert back to a bigint by simply using `BigInt(value)`.
> Add `largeBigIntToString` config option

- README.md
- index.d.ts
- tests/test.js
- unpack.js
Hello Kris 👋
This PR introduces support for using arrays of stringable primitives as Map keys. It ensures that when retrieving the map key, arrays are validated to confirm all elements are of valid types and then converted to a string representation. This enhancement addresses a use case where array-based keys are required.
Example:
```javascript
asSafeString(['john', 12, [3.14, true, Infinity]]);
// -> john,12,3.14,true,Infinity'
```
> Support array to string conversion for keys

- pack.js
- tests/test.js
- unpack.js
Hey Kris,
`msgpackr` currently has pretty decent support for the structured clone algorithm, but there's still a few gaps that I'd like to help fix. This PR implements support for encoding larger bigint values and more error types.
Bigints are currently limited to 2^1023. Removing the limit outright leads to poor decoding performance with large values due to an `O(n^2)` time complexity, and I explored a few solutions and benchmarked them:
- The original algorithm (`O(n^2)`) decodes the bigint byte by byte, and decoding each byte require a shift with linear time complexity.
- The first optimization (`O(n^2)`) gives a >8x speedup using a `DataView` to read 8 bytes at a time.
- The second optimization (`O(n log n)`) gives a >1000x speedup with larger buffers by recursively dividing the …
> Add support for larger bigints and more error types

- pack.js
- tests/test.js
- unpack.js
This is a followup to #158:
- implement encoding bigints using a hex string for very large values to avoid a quadratic time complexity
- implement recursive `Map`s and `Set`s
- implement serializing `DataView` instances
> Add support for recursive maps, sets, and DataViews

- package.json
Currently, `msgpackr` can't run on cloudflare workers because they appear to resolve the `node` entrypoint. Explicitly adding the `browser` entrypoint before (entrypoint options are resolved one after the other), resolves this.
> support cloudflare workers

- pack.js
- tests/test.js
- unpack.js
This commit unreverts #158, fixes the regression in 715de16, and adds additional tests.
The fix is equivalent to this:
```diff
while (true) {
chunks.push(value & mask)
-		if ((value >> BigInt(64)) === empty) break
+		if ((value >> BigInt(63)) === empty) break
value >>= BigInt(64)
}
```
The original code incorrectly handle numbers with a bit length that's exactly a multiple of 64. The new tests test a number for each possible bit length.
> Unreverts #158 and fix regression

- pack.js
The useBuffer() method was not properly initializing the module-level targetView variable, causing `TypeError: undefined is not an object (evaluating 'targetView.setFloat64')` and similar errors when packing data that requires DataView operations.
When useBuffer(buffer) is called, it correctly sets:
- ✅ target = buffer
- ✅ position = 0
- ❌ targetView remains undefined
Later, when pack() executes, it checks if (!target) to decide whether to initialize. Since target is already set by useBuffer(), the initialization block that sets targetView = target.dataView is skipped, leaving targetView undefined.
Added targetView = target.dataView to useBuffer() to ensure both target and targetView are properly initialized when using external buffers.
This enables proper buffer reuse patterns and …
> Fix useBuffer() targetView assignment
